### PR TITLE
Fix handling of responses where content is `bytes`

### PR DESCRIPTION
**Pull request by thule0**
This ensures responses with bytes content is handled correctly.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@roman-alexeev:

Thank you!

**Comment by thule0** [comment]
No problem!
Do you mind making a release?

**Comment by barseghyanartur** [comment]
@roman-alexeev:

Tonight. :)

**Comment by thule0** [comment]
Cool, thank you!

**Comment by barseghyanartur** [comment]
Done in 0.1.6.

**Pull request merged**
